# Generated by Django 6.1.1 on 2026-10-01 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuelStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis_id', models.PositiveIntegerField(help_text='OPIS Truckstop ID.', unique=True)),
                ('name', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=80)),
                ('state', models.CharField(max_length=2)),
                ('rack_id', models.PositiveIntegerField(blank=True, null=True)),
                ('retail_price', models.DecimalField(decimal_places=3, help_text='US dollars per gallon.', max_digits=6)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
            options={
                'ordering': ['opis_id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('retail_price__gt', 0)), name='fuel_station_price_positive')],
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Output of normalize_place_name().', max_length=80)),
                ('state', models.CharField(max_length=2)),
                ('name', models.CharField(max_length=120)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('population', models.PositiveIntegerField(default=0)),
                ('ambiguous', models.BooleanField(default=False, help_text='Another same-name place exists elsewhere in the state and population cannot tell them apart. Fine as a best guess for a trip endpoint; never used to position a fuel station.')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('key', 'state'), name='unique_place_key')],
            },
        ),
    ]
